"""Tests for the pieces that existed but were not connected to anything.

Each of these covers a gap where the logic was implemented and tested in
isolation while nothing actually called it -- the failure mode where every unit
test passes and the feature does not exist.
"""

from __future__ import annotations

import pytest

from akira.audit import AuditLog, log_path
from akira.chat import Conversation
from akira.lock.pipeline import PipelineResponder
from akira.models import ModelManager, ModelSpec, Role
from akira.models.scripted import ScriptedBackend
from akira.personality.defaults import default_personality
from akira.plugins import EXAMPLE_PLUGIN, digest_of, discover, plugin_dir
from akira.plugins import load as load_plugins
from akira.projects import ensure_project
from akira.schemas import Manifest, SchemaError, Settings
from akira.store import bootstrap_vault


@pytest.fixture
def vault(tmp_path):
    root = tmp_path / "vault"
    root.mkdir()
    bootstrap_vault(root)
    ensure_project(root, "default")
    return root


def build(vault, *, tier=2, memory_enabled=True, main_reply="ok", logging=False):
    manifest = Manifest.initial().with_unlocked("physics").with_trust_tier(tier)
    settings = Settings.from_json({
        "models": {"main_path": "m.gguf", "auditor_path": "a.gguf", "loading": "concurrent"},
        "memory": {"enabled": memory_enabled},
        "logging_enabled": logging,
    })
    main = ScriptedBackend(ModelSpec(path="m.gguf", role=Role.MAIN), patterns=[(r".*", main_reply)])
    auditor = ScriptedBackend(ModelSpec(path="a.gguf", role=Role.AUDITOR), patterns=[(r".*", "VERDICT: PASS")])
    manager = ModelManager(settings, factory=lambda s: main if s.role is Role.MAIN else auditor)
    audit = AuditLog(vault, enabled=logging)
    responder = PipelineResponder(
        vault, manifest, settings, default_personality(), manager, project="default", audit=audit
    )
    return responder, main, audit


# --- the remember() tool actually reaches the model ------------------------


def test_tool_description_is_injected_at_tier_two(vault):
    # Previously defined and never injected: the parser worked, the gated write
    # path worked, and MAIN was never told the tool existed.
    responder, main, _ = build(vault, tier=2)
    responder.respond("hello", Conversation())
    assert "REMEMBER:" in main.calls[0][0].content


def test_tool_description_is_absent_at_tier_zero(vault):
    responder, main, _ = build(vault, tier=0)
    responder.respond("hello", Conversation())
    assert "REMEMBER:" not in main.calls[0][0].content


def test_tool_description_is_absent_at_tier_one(vault):
    # Tier 1 allows user-pinned memory only. Advertising the tool would have the
    # model emit calls that are parsed, refused by the tier check, and reported
    # to the user as failures -- noise generated by our own prompt.
    responder, main, _ = build(vault, tier=1)
    responder.respond("hello", Conversation())
    assert "REMEMBER:" not in main.calls[0][0].content


def test_tool_description_is_absent_when_memory_is_disabled(vault):
    responder, main, _ = build(vault, tier=2, memory_enabled=False)
    responder.respond("hello", Conversation())
    assert "REMEMBER:" not in main.calls[0][0].content


def test_tool_description_sits_before_the_lock_directive(vault):
    responder, main, _ = build(vault, tier=2)
    responder.respond("hello", Conversation())
    prompt = main.calls[0][0].content
    assert prompt.index("REMEMBER:") < prompt.index("KNOWLEDGE CONSTRAINT")
    assert prompt.rstrip().endswith("the list above still governs.")


def test_tool_description_is_dropped_whole_under_budget_pressure(vault):
    # All-or-nothing: a half-truncated description produces malformed REMEMBER
    # lines the parser drops, so the model would look like it was recording
    # things while nothing reached disk.
    from akira.context.assembly import ContextAssembler

    def words(text: str) -> int:
        return len(text.split())

    settings = Settings.from_json({"context": {"total_budget_tokens": 512, "reserve_for_response": 64}})
    assembler = ContextAssembler(settings, words)

    # The description is ~76 words, so the squeeze has to be decisive: a long
    # user message plus the never-truncated directive leaves nothing over.
    roomy = assembler.assemble(
        manifest=Manifest.initial().with_unlocked("physics"),
        personality=default_personality(),
        user_text="what is gravity?",
        memory_tool=True,
    )
    assert roomy.section("remember() tool").text.startswith("You have one tool")

    squeezed = assembler.assemble(
        manifest=Manifest.initial().with_unlocked("physics"),
        personality=default_personality(),
        user_text="x " * 400,
        memory_tool=True,
    )
    section = squeezed.section("remember() tool")
    assert section is not None
    assert section.text == "", "the description must be dropped whole, never trimmed"
    assert section.tokens == 0
    assert any("remember() tool" in n for n in squeezed.notices)
    # And the directive still survives intact, which is the point of the order.
    assert "KNOWLEDGE CONSTRAINT" in squeezed.system_prompt


def test_tool_description_names_the_exact_unlocked_topics(vault):
    """Observed with the real model: an answer about gravity proposed
    `topic: "gravity"` while only `physics` was unlocked, so the write was
    refused and nothing reached disk. The description now lists the valid ids."""
    from akira.memory.live import remember_tool_description

    text = remember_tool_description(("physics", "python_basics"))
    assert "MUST be exactly one of: physics, python_basics" in text
    assert "Do not invent a narrower name" in text


def test_tool_description_with_nothing_unlocked_says_not_to_call_it():
    from akira.memory.live import remember_tool_description

    assert "do not call this tool" in remember_tool_description(())


def test_injected_tool_description_carries_the_live_topic_list(vault):
    responder, main, _ = build(vault, tier=2)
    responder.respond("hello", Conversation())
    prompt = main.calls[0][0].content
    assert "MUST be exactly one of: physics" in prompt


def test_tool_section_is_reported_in_the_viewer(vault):
    responder, _, _ = build(vault, tier=2)
    turn = responder.respond("hello", Conversation())
    assert "remember() tool" in turn.prompt_view


# --- audit log --------------------------------------------------------------


def test_log_is_not_written_when_disabled(vault):
    responder, _, _ = build(vault, logging=False)
    responder.respond("hello", Conversation())
    assert not log_path(vault).exists()


def test_log_records_gate_decisions_when_enabled(vault):
    responder, _, _ = build(vault, logging=True)
    responder.respond("hello", Conversation())
    text = log_path(vault).read_text(encoding="utf-8")
    assert "gate=response" in text
    assert "allow" in text
    assert "layer=" in text


def test_log_never_contains_the_draft_or_the_prompt(vault):
    # A log holding blocked drafts would be a plaintext copy of exactly what the
    # lock system withheld, sitting in the vault where retrieval could find it.
    secret_reply = "Sodium reacts violently with water"
    secret_prompt = "tell me about zzunusualtokenzz"
    responder, _, _ = build(vault, logging=True, main_reply=secret_reply)
    responder.respond(secret_prompt, Conversation())
    text = log_path(vault).read_text(encoding="utf-8")
    assert "Sodium" not in text
    assert "zzunusualtokenzz" not in text


def test_log_records_events_with_metadata_only(vault):
    audit = AuditLog(vault, enabled=True)
    audit.event("trust_tier_changed", tier=2)
    text = log_path(vault).read_text(encoding="utf-8")
    assert "event=trust_tier_changed" in text
    assert "tier=2" in text


def test_log_failure_never_raises(tmp_path):
    # A full disk is not a reason to withhold a response that already passed.
    audit = AuditLog(tmp_path / "nonexistent" / "deeply" / "nested", enabled=True)
    audit.event("smoke")  # must not raise


# --- plugin loading ---------------------------------------------------------


def write_plugin(vault, name="demo", body=None):
    path = plugin_dir(vault) / f"{name}.py"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body if body is not None else EXAMPLE_PLUGIN, encoding="utf-8")
    return path


def test_discover_does_not_import(vault):
    write_plugin(vault, "boom", body="raise RuntimeError('imported!')\n")
    found = discover(vault)
    assert [f.name for f in found] == ["boom"]


def test_unapproved_plugin_is_not_loaded(vault):
    responder, _, _ = build(vault)
    write_plugin(vault)
    loaded, errors = load_plugins(
        vault, responder.manifest, responder.settings, responder.gate(), responder.manager, enabled={}
    )
    assert loaded == [] and errors == []


def test_approved_plugin_loads_and_contributes_a_menu_item(vault):
    responder, _, _ = build(vault)
    path = write_plugin(vault)
    loaded, errors = load_plugins(
        vault, responder.manifest, responder.settings, responder.gate(), responder.manager,
        enabled={"demo": digest_of(path)},
    )
    assert errors == []
    assert len(loaded) == 1
    plugin, context = loaded[0]
    assert plugin.name == "word-count"
    assert [label for label, _ in context.menu_items] == ["Count words"]


def test_changed_plugin_is_refused(vault):
    responder, _, _ = build(vault)
    path = write_plugin(vault)
    stale = digest_of(path)
    path.write_text(EXAMPLE_PLUGIN + "\n# edited after approval\n", encoding="utf-8")

    loaded, errors = load_plugins(
        vault, responder.manifest, responder.settings, responder.gate(), responder.manager,
        enabled={"demo": stale},
    )
    assert loaded == []
    assert any("changed since it was approved" in e for e in errors)


def test_broken_plugin_reports_rather_than_crashing(vault):
    responder, _, _ = build(vault)
    path = write_plugin(vault, body="raise RuntimeError('boom')\n")
    loaded, errors = load_plugins(
        vault, responder.manifest, responder.settings, responder.gate(), responder.manager,
        enabled={"demo": digest_of(path)},
    )
    assert loaded == []
    assert any("import failed" in e for e in errors)


def test_plugin_without_the_expected_attribute_is_reported(vault):
    responder, _, _ = build(vault)
    path = write_plugin(vault, body="X = 1\n")
    loaded, errors = load_plugins(
        vault, responder.manifest, responder.settings, responder.gate(), responder.manager,
        enabled={"demo": digest_of(path)},
    )
    assert loaded == []
    assert any("PROTEGE_PLUGIN" in e for e in errors)


def test_plugin_context_gates_generated_output(vault):
    # Extensions inherit gating by construction: the context hands out
    # generate_checked, never a raw backend.
    from akira.models import ChatMessage

    responder, _, _ = build(vault)
    path = write_plugin(vault)
    loaded, _ = load_plugins(
        vault, responder.manifest, responder.settings, responder.gate(), responder.manager,
        enabled={"demo": digest_of(path)},
    )
    _, context = loaded[0]
    assert not hasattr(context, "backend")
    result = context.generate_checked([ChatMessage(role="user", content="hi")])
    assert isinstance(result, str)


def test_plugin_context_returns_a_gate_result_when_blocked(vault):
    import json

    from akira.models import ChatMessage
    from akira.store import tripwire_dir

    (tripwire_dir(vault) / "chemistry.json").write_text(
        json.dumps({"topic": "chemistry", "keywords": ["sodium"]}), encoding="utf-8"
    )
    responder, _, _ = build(vault, main_reply="Sodium reacts with water.")
    path = write_plugin(vault)
    loaded, _ = load_plugins(
        vault, responder.manifest, responder.settings, responder.gate(), responder.manager,
        enabled={"demo": digest_of(path)},
    )
    _, context = loaded[0]
    result = context.generate_checked([ChatMessage(role="user", content="hi")])
    assert not isinstance(result, str)
    assert result.layer == "tripwires"


# --- settings schema --------------------------------------------------------


def test_enabled_plugins_round_trips(vault):
    digest = "a" * 64
    settings = Settings.from_json({"enabled_plugins": {"demo": digest}})
    assert Settings.from_json(settings.to_json()).enabled_plugins == {"demo": digest}


def test_enabled_plugins_rejects_a_bad_digest():
    with pytest.raises(SchemaError, match="hex digest"):
        Settings.from_json({"enabled_plugins": {"demo": "not-a-digest"}})


def test_netguard_setting_is_gone():
    # The toggle existed and did nothing -- the guard installs unconditionally.
    # A setting that lies is worse than no setting.
    assert not hasattr(Settings(), "netguard_enabled")
    assert "netguard_enabled" not in Settings().to_json()


def test_unknown_legacy_keys_are_ignored_not_fatal():
    # An older settings.json carrying netguard_enabled must still load.
    settings = Settings.from_json({"netguard_enabled": False, "logging_enabled": True})
    assert settings.logging_enabled
