"""Saving and reloading conversations.

One JSON file per conversation, in a flat directory. Not a database: the
working set is a few hundred small files, a directory listing is fast enough to
build the sidebar from, and a file you can read, copy or delete with ordinary
tools is worth more here than query power nobody asked for.

Every write is atomic. A crash mid-save must not leave a conversation that
fails to parse on the next launch — losing the last turn is survivable, losing
the whole thread is not.
"""

from __future__ import annotations

import json
import os
import re
import tempfile
from dataclasses import dataclass
from pathlib import Path

from .config import config_dir
from .conversation import Conversation, Message
from akira.core import files

#: Ids are generated by `secrets.token_hex`, so this is a validation rule
#: rather than a sanitiser: anything else is refused rather than cleaned up.
#: An id reaching the filesystem is a path, and a path built from unvalidated
#: input is a traversal waiting to happen.
_ID = re.compile(r"\A[0-9a-f]{8,64}\Z")

#: Guards against a corrupt or hand-edited file claiming to be enormous.
MAX_BYTES = 8 * 1024 * 1024


class ConversationError(RuntimeError):
    """A conversation could not be read or written."""


@dataclass(frozen=True)
class Summary:
    """Enough to draw a sidebar row without opening the file."""

    id: str
    title: str
    updated: float
    turns: int


def conversations_dir() -> Path:
    return config_dir() / "conversations"


def _validate(conversation_id: str) -> str:
    if not _ID.match(conversation_id):
        raise ConversationError(f"not a conversation id: {conversation_id!r}")
    return conversation_id


class ConversationStore:
    """The saved conversations on disk."""

    def __init__(self, directory: Path | None = None) -> None:
        self._dir = directory if directory is not None else conversations_dir()

    @property
    def directory(self) -> Path:
        return self._dir

    def _path(self, conversation_id: str) -> Path:
        return self._dir / f"{_validate(conversation_id)}.json"

    # -- writing ------------------------------------------------------------

    def save(self, conversation: Conversation) -> None:
        """Write a conversation, atomically.

        A conversation with no real exchange is deleted rather than written —
        opening the app, thinking better of it and closing should not leave an
        "New chat" in the sidebar forever.
        """
        if not any(m.role == "user" and m.text.strip() for m in conversation.messages):
            self.delete(conversation.id)
            return

        payload = {
            "id": conversation.id,
            "title": conversation.title or conversation.derive_title(),
            "system_prompt": conversation.system_prompt,
            # The project it was held in, so what is distilled from it is filed
            # under that project. Empty outside any project.
            "project": conversation.project,
            "messages": [
                {
                    "id": m.id,
                    "role": m.role,
                    "text": m.text,
                    "created": m.created,
                    "error": m.error,
                }
                for m in conversation.messages
                # A placeholder that never received a token is an artefact of
                # streaming, not part of the conversation.
                if m.text.strip()
            ],
        }

        target = self._path(conversation.id)
        target.parent.mkdir(parents=True, exist_ok=True)

        handle, tmp_name = tempfile.mkstemp(
            dir=str(target.parent), prefix=".conv-", suffix=".tmp"
        )
        tmp = Path(tmp_name)
        try:
            with os.fdopen(handle, "w", encoding="utf-8") as fh:
                json.dump(payload, fh, ensure_ascii=False)
                fh.flush()
                os.fsync(fh.fileno())
            files.replace(tmp, target)
        except BaseException:
            tmp.unlink(missing_ok=True)
            raise

    def delete(self, conversation_id: str) -> None:
        try:
            self._path(conversation_id).unlink(missing_ok=True)
        except ConversationError:
            # Deleting something that could never have been saved is a no-op,
            # not an error.
            return

    # -- reading ------------------------------------------------------------

    def load(self, conversation_id: str) -> Conversation:
        path = self._path(conversation_id)
        try:
            raw = path.read_text(encoding="utf-8")
        except OSError as exc:
            raise ConversationError(f"could not read {path.name}: {exc}") from exc

        if len(raw) > MAX_BYTES:
            raise ConversationError(f"{path.name} is implausibly large")

        try:
            data = json.loads(raw)
        except json.JSONDecodeError as exc:
            raise ConversationError(f"{path.name} is not valid JSON: {exc}") from exc

        if not isinstance(data, dict):
            raise ConversationError(f"{path.name} does not contain a conversation")

        conversation = Conversation(
            id=str(data.get("id") or conversation_id),
            title=str(data.get("title") or ""),
            project=str(data.get("project") or ""),
        )
        prompt = data.get("system_prompt")
        if isinstance(prompt, str) and prompt:
            conversation.system_prompt = prompt

        for entry in data.get("messages") or []:
            if not isinstance(entry, dict):
                continue
            role = str(entry.get("role", ""))
            if role not in ("user", "assistant", "system"):
                continue
            message = Message(
                role=role,
                text=str(entry.get("text", "")),
                error=bool(entry.get("error", False)),
            )
            if isinstance(entry.get("id"), str):
                message.id = entry["id"]
            if isinstance(entry.get("created"), (int, float)):
                message.created = float(entry["created"])
            conversation.messages.append(message)

        return conversation

    def list(self, limit: int = 200) -> list[Summary]:
        """Summaries, most recently updated first.

        A file that fails to parse is skipped rather than raising. One corrupt
        conversation must not make the sidebar unbuildable.
        """
        if not self._dir.is_dir():
            return []

        found: list[Summary] = []
        for path in self._dir.glob("*.json"):
            try:
                stat = path.stat()
                if stat.st_size > MAX_BYTES:
                    continue
                data = json.loads(path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                continue
            if not isinstance(data, dict):
                continue

            messages = data.get("messages")
            found.append(
                Summary(
                    id=str(data.get("id") or path.stem),
                    title=str(data.get("title") or "Untitled"),
                    updated=stat.st_mtime,
                    turns=len(messages) if isinstance(messages, list) else 0,
                )
            )

        found.sort(key=lambda s: s.updated, reverse=True)
        return found[:limit]


#: Thresholds for `relative_time`, longest-lived last.
_MINUTE = 60
_HOUR = 60 * _MINUTE
_DAY = 24 * _HOUR
_WEEK = 7 * _DAY


def relative_time(timestamp: float, now: float | None = None) -> str:
    """A short age for a sidebar row: ``now``, ``5m``, ``2h``, ``Mon``, ``12 Mar``.

    Deliberately coarse and deliberately short. The column is narrow and the
    question a reader is actually asking is "was this today or a while ago",
    which a precise timestamp answers less well than a rough one.
    """
    import time

    current = time.time() if now is None else now
    delta = max(0.0, current - timestamp)

    if delta < _MINUTE:
        return "now"
    if delta < _HOUR:
        return f"{int(delta // _MINUTE)}m"
    if delta < _DAY:
        return f"{int(delta // _HOUR)}h"
    if delta < _WEEK:
        # Within the week a weekday name is more use than "3d" — people
        # remember doing things on Tuesday, not three days ago.
        return time.strftime("%a", time.localtime(timestamp))
    return time.strftime("%d %b", time.localtime(timestamp)).lstrip("0")
